"""Add tenant scope to RBAC with RLS

Revision ID: 27f0d6d11564
Revises: 2245c3811a6e
Create Date: 2025-12-24 22:13:38.754396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f0d6d11564'
down_revision: Union[str, None] = '2245c3811a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('tasks', ... ) # Removed duplicate table creation

    op.add_column('permissions', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_permissions_codename'), table_name='permissions')
    op.create_index(op.f('ix_permissions_tenant_id'), 'permissions', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'permissions', ['codename', 'tenant_id'], postgresql_nulls_not_distinct=False)
    
    op.add_column('roles', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'roles', ['name', 'tenant_id'], postgresql_nulls_not_distinct=False)
    
    # --- RLS Policies ---
    
    # Users
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_users ON users
        USING (tenant_id = current_setting('app.current_tenant_id', true)::int)
    """)

    # Roles
    op.execute("ALTER TABLE roles ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_roles ON roles
        USING (tenant_id = current_setting('app.current_tenant_id', true)::int OR tenant_id IS NULL)
    """)

    # Permissions
    op.execute("ALTER TABLE permissions ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_permissions ON permissions
        USING (tenant_id = current_setting('app.current_tenant_id', true)::int OR tenant_id IS NULL)
    """)

    # User Roles
    op.execute("ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_user_roles ON user_roles
        USING (
            EXISTS (
                SELECT 1 FROM users 
                WHERE users.id = user_roles.user_id 
                AND users.tenant_id = current_setting('app.current_tenant_id', true)::int
            )
        )
    """)

    # Role Permissions
    op.execute("ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_role_permissions ON role_permissions
        USING (
            EXISTS (
                SELECT 1 FROM roles 
                WHERE roles.id = role_permissions.role_id 
                AND (roles.tenant_id = current_setting('app.current_tenant_id', true)::int OR roles.tenant_id IS NULL)
            )
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop RLS Policies
    op.execute("DROP POLICY IF EXISTS tenant_isolation_role_permissions ON role_permissions")
    op.execute("ALTER TABLE role_permissions DISABLE ROW LEVEL SECURITY")

    op.execute("DROP POLICY IF EXISTS tenant_isolation_user_roles ON user_roles")
    op.execute("ALTER TABLE user_roles DISABLE ROW LEVEL SECURITY")

    op.execute("DROP POLICY IF EXISTS tenant_isolation_permissions ON permissions")
    op.execute("ALTER TABLE permissions DISABLE ROW LEVEL SECURITY")

    op.execute("DROP POLICY IF EXISTS tenant_isolation_roles ON roles")
    op.execute("ALTER TABLE roles DISABLE ROW LEVEL SECURITY")
    
    op.execute("DROP POLICY IF EXISTS tenant_isolation_users ON users")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY")

    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_column('roles', 'tenant_id')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_tenant_id'), table_name='permissions')
    op.create_index(op.f('ix_permissions_codename'), 'permissions', ['codename'], unique=True)
    op.drop_column('permissions', 'tenant_id')
    # op.drop_table('tasks') # Removed duplicate table drop
    # ### end Alembic commands ###
